name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'rio_stac/**.py'
      - .github/workflows/deploy_mkdocs.yml

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .["docs"]

      - name: Deploy docs
        run: mkdocs gh-deploy -f docs/mkdocs.yml --force
